<a href="https://colab.research.google.com/github/eshitamalhotraaaa/datasciencecoursera/blob/master/Copy_of_KNN_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib notebook

In [ ]:
#train dataset
path = "/content/drive/MyDrive/Colab_CSV/Covid_Data.csv"
dataset = pd.read_csv(path)

In [ ]:
dataset.head()

Serial Number  ...           Label
0              1  ...     Informative
1              2  ...  Non-Actionable
2              3  ...  Non-Actionable
3              4  ...  Non-Actionable
4              5  ...     Informative

[5 rows x 4 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Serial Number  400 non-null    int64  
 1   Tweet ID       400 non-null    float64
 2   Tweet Content  400 non-null    object 
 3   Label          400 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 12.6+ KB


In [ ]:
A = dataset['Tweet Content'].values

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
 
vectorizer=TfidfVectorizer()
vectorizer.fit(A)
A=vectorizer.transform(A)

In [ ]:
mapping_dataCol = {'Non-Actionable':0,'Informative':1,'Debatable':2,'Other Fraud':3,'Party Politics':4,
'Actionable':5,'Negative':6}

# mapping_dataCol = {'N':0, 'A':1}
dataset["Label"]=dataset["Label"].map(mapping_dataCol)

In [ ]:
# Non-Actionable
sum(dataset['Label'] == 0) 

206

In [ ]:
#Informative
sum(dataset['Label'] == 1) 

96

In [ ]:
#Debatable
sum(dataset['Label'] == 2) 

35

In [ ]:
#Other Frauds
sum(dataset['Label'] == 3) 

22

In [ ]:
#Party Politics
sum(dataset['Label'] == 4) 

11

In [ ]:
#Actionable
sum(dataset['Label'] == 5) 

18

In [ ]:
#Negative
sum(dataset['Label'] == 6) 

12

In [ ]:
dataset["Label"].value_counts()


0    206
1     96
2     35
3     22
5     18
6     12
4     11
Name: Label, dtype: int64

In [ ]:
#To check if any values are NULL or are missing
dataset.isnull().sum()

Serial Number    0
Tweet ID         0
Tweet Content    0
Label            0
dtype: int64

In [ ]:
#To check if any values are NULL or are missing in Boolean

dataset.isnull().values

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#Taking all the rows and only the Tweet Content Column
X = dataset.iloc[:, 2]

In [ ]:
X.head()

0    And if you found something fishy just informed...
1    Canada\u2019s cyber spies taking down sites as...
2    @MehHarshil Lol.... Yes, it is true...and you ...
3    India would  have  been saved if the politicia...
4    Mumbai Covid vaccine scam: Probe says victims ...
Name: Tweet Content, dtype: object

In [ ]:
X = X.values

In [ ]:
X = pd.get_dummies(X)

In [ ]:
X

"@BAMPI The scam is too much anybody coming into Nigeria is required to pay for Covid 19 test 51k and their is no follow up to know if you have the test or not they are only bothered about the 51k they're collecting"  ...  why SC has appointed 12 members to look after covid situation his hardwork everywhere no oxygen no bed no vaccine no ration only VISTA &amp; HIS OWN PALACE rafeal 30.000 Crore scam its his hardwork yes
0                                                    0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
1                                                    0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
2                                                    0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
3                                                    0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
4                                                    0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
..                                                 ...                                                                                                                                                                          ...                                                ...                                                                                                                                                        
395                                                  0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
396                                                  0                                                                                                                                                                          ...                                                  0                                                                                                                                                        
397                                                  0                                                                         

In [ ]:
#To only select the Label Column, which is the last column
Y = dataset.iloc[:, -1].values

In [ ]:
Y

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 4, 0, 1, 1, 4,
       4, 4, 4, 4, 4, 5, 0, 0, 1, 5, 0, 5, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0,
       4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 5, 0, 1, 0, 0, 0, 1, 0, 0, 0, 5, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 6, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 0, 3, 6, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 2, 3, 1, 0, 3, 4, 3, 6, 1, 1, 5, 6, 2, 1, 3, 3, 2, 1, 0, 1,
       3, 3, 0, 0, 1, 3, 1, 3, 0, 0, 1, 1, 0, 0, 1, 2, 2, 0, 0, 0, 1, 6,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 2, 0, 1, 2, 2, 0, 1,
       3, 3, 1, 3, 2, 2, 0, 3, 2, 0, 1, 2, 1, 0, 6, 1, 0, 2, 1, 2, 0, 3,
       1, 1, 0, 1, 2, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 2, 2, 5, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 2, 1, 0, 1, 1, 6, 2, 0, 1, 1, 1, 0,
       1, 1, 1, 2, 1, 2, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

**SPLITTING THE DATASET**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#Test Data size : Train Data Size = 20 : 80 
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=1) 
#stratified train test split in sklearn

In [ ]:
#Importing the library to help in finding the KNN Neighbours
from sklearn.neighbors import KNeighborsClassifier 

In [ ]:
KNN = KNeighborsClassifier(n_neighbors = 5, 
                           weights = 'uniform',
                           algorithm = 'kd_tree',
                           leaf_size = 30,
                           p =2,
                           metric = 'minkowski',
                           n_jobs = -1)

In [ ]:
KNN.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='kd_tree', n_jobs=-1)

In [ ]:
KNN.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
Y_pred = KNN.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

**Classification Report**

In [ ]:
print(classification_report(Y_test.reshape(-1,1), Y_pred))

              precision    recall  f1-score   support

           0       0.62      1.00      0.77        50
           1       0.00      0.00      0.00        18
           2       0.00      0.00      0.00         3
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         2

    accuracy                           0.62        80
   macro avg       0.10      0.17      0.13        80
weighted avg       0.39      0.62      0.48        80



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy score for KNN is: ", accuracy_score(Y_test, Y_pred) * 100, '%')

Accuracy score for KNN is:  62.5 %


**DATA AUGMENTATION**

In [ ]:
pip install imblearn

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE()

In [ ]:
X_train_smote, Y_train_smote = smote.fit_resample(X_train.astype('float'), Y_train)

In [ ]:
from collections import Counter

In [ ]:
print("Before SMOTE: ", Counter(Y_train))
print("After SMOTE: ", Counter(Y_train_smote))

Before SMOTE:  Counter({0: 156, 1: 78, 2: 32, 5: 18, 3: 17, 6: 10, 4: 9})
After SMOTE:  Counter({0: 156, 4: 156, 1: 156, 3: 156, 5: 156, 2: 156, 6: 156})


In [ ]:
KNN.fit(X_train_smote, Y_train_smote)
Y_pred = KNN.predict(X_test)
print("Accuracy score for KNN is: ", accuracy_score(Y_test, Y_pred) * 100, '%')

Accuracy score for KNN is:  3.75 %


In [ ]:
pd.crosstab(Y_test, Y_pred)

col_0   2
row_0    
0      50
1      18
2       3
3       5
4       2
6       2

In [ ]:
Y_pred = KNN.predict(X_test)
print(classification_report(Y_test.reshape(-1,1), Y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        50
           1       0.00      0.00      0.00        18
           2       0.04      1.00      0.07         3
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         2

    accuracy                           0.04        80
   macro avg       0.01      0.17      0.01        80
weighted avg       0.00      0.04      0.00        80



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
